import json

BEVERAGE_ITEMS_EN = [
    # --- WHITE WINES ---
    {
        "id": "bile-ryzlink-gotberg",
        "name": "Ryzlink Rýnský Gotberg (Riesling)",
        "category": "wine_white",
        "categoryName": "White Wines",
        "producer": "Gotberg Winery",
        "origin": "Czech Republic",
        "region": "Moravia, Mikulov subregion, Popice (Svidrny vineyard)",
        "volume": "0.75l (also by the glass 0.15l)",
        "abv": "12.5% ABV",
        "price": "590 CZK (bottle) / 118 CZK (glass)",
        "rawIngredients": "100% Rhine Riesling grape variety grown on loess and limestone soils of the Pálava Hills.",
        "productionProcess": "Gentle whole-cluster pressing, temperature-controlled stainless steel fermentation, followed by extended maturation on fine lees (sur-lie).",
        "flavorProfile": "Crisp mineral wine with notes of linden blossom, dried apricots, green apple, and subtle petrol minerality backed by vibrant acidity.",
        "foodPairing": "Pairs beautifully with hand-cut beef tartare, trout fillet, veal sausage with morels, and fresh cheeses.",
        "staffNotes": "A classic benchmark of Moravian Riesling from Popice. Bone dry, juicy, exceptionally drinkable with a long mineral finish.",
        "tags": ["wine", "white wine", "Moravia", "Gotberg", "dry"]
    },
    {
        "id": "bile-pinot-gris-reisten",
        "name": "Pinot Gris Reisten (Maidenburg)",
        "category": "wine_white",
        "categoryName": "White Wines",
        "producer": "Reisten Winery",
        "origin": "Czech Republic",
        "region": "Moravia, Mikulov subregion, Pavlov (Maidenburg vineyard)",
        "volume": "0.75l",
        "abv": "13.0% ABV",
        "price": "680 CZK",
        "rawIngredients": "100% Pinot Gris grown on the steep limestone slopes of Pálava Protected Landscape Area.",
        "productionProcess": "Fermented in stainless steel, with a portion aged in large neutral oak casks. Extended lees contact enhancing full mouthfeel.",
        "flavorProfile": "Rich, opulent, and extract-driven wine showing ripe butter pear, candied orange peel, honeycomb, and a gentle bready finish.",
        "foodPairing": "Outstanding with roast pork belly with caramelized yuzu sauce, braised beef, and roasted chicken.",
        "staffNotes": "For guests seeking a rounder, fuller-bodied white with softer acidity and creamy texture.",
        "tags": ["wine", "white wine", "Pinot Gris", "Pálava", "Reisten"]
    },
    {
        "id": "bile-hibernal-bilkovi",
        "name": "Hibernal Bílkovi",
        "category": "wine_white",
        "categoryName": "White Wines",
        "producer": "Bílkovi Winery",
        "origin": "Czech Republic",
        "region": "Moravia, Velké Pavlovice subregion, Velké Bílovice",
        "volume": "0.75l",
        "abv": "12.5% ABV",
        "price": "540 CZK",
        "rawIngredients": "100% Hibernal – modern PIWI fungus-resistant hybrid variety bred from Seibel and Rhine Riesling.",
        "productionProcess": "Reductive stainless steel vinification prioritizing fruit preservation and vibrant aromatic aromatics.",
        "flavorProfile": "Intensely aromatic bouquet of blackcurrant leaf, ripe peach, gooseberry, elderflower, and fresh citrus.",
        "foodPairing": "Excellent with Asian fusion flavors, goat cheese salads, and crispy fried chicken croquettes.",
        "staffNotes": "Ideal recommendation for guests looking for Sauvignon Blanc-like aromatic intensity paired with vibrant freshness.",
        "tags": ["wine", "white wine", "Hibernal", "aromatic", "Bílkovi"]
    },
    {
        "id": "bile-sauvignon-halkoci",
        "name": "Sauvignon Halkoci",
        "category": "wine_white",
        "categoryName": "White Wines",
        "producer": "Halkoci Winery",
        "origin": "Czech Republic",
        "region": "Moravia, Znojmo / Mikulov subregion",
        "volume": "0.75l",
        "abv": "12.5% ABV",
        "price": "580 CZK",
        "rawIngredients": "100% Sauvignon Blanc from mature Moravian vineyard plots.",
        "productionProcess": "Temperature-controlled cool fermentation preserving delicate pyrazine and citrus thiols.",
        "flavorProfile": "Crisp notes of freshly mown grass, gooseberry, nettles, kiwi, and lime zest backed by ringing acidity.",
        "foodPairing": "Perfect with creamy lobster soup, wood-fired fish, and dishes dressed with fresh fines herbes sauce.",
        "staffNotes": "A dry, mouthwatering Sauvignon Blanc with classic cool-climate herbal precision.",
        "tags": ["wine", "white wine", "Sauvignon", "crisp", "Moravia"]
    },
    {
        "id": "bile-ryzlink-vlassky-sukal",
        "name": "Welschriesling Šukal (Ryzlink Vlašský)",
        "category": "wine_white",
        "categoryName": "White Wines",
        "producer": "Milan Šukal",
        "origin": "Czech Republic",
        "region": "Moravia, Slovácko subregion, Nový Poddvorov",
        "volume": "0.75l",
        "abv": "13.0% ABV",
        "price": "650 CZK",
        "rawIngredients": "100% Welschriesling (Ryzlink vlašský) from low-yield family vineyards.",
        "productionProcess": "Artisanal low-intervention vinification, spontaneous yeast fermentation, prolonged maturation on lees.",
        "flavorProfile": "Characteristic mineral salinity, dried meadow herbs, crisp green apples, dried raisins, and roasted walnuts.",
        "foodPairing": "Superb with roast pork knuckle, Duroc schnitzel, and hearty Central European fare.",
        "staffNotes": "Milan Šukal is among Moravia's most celebrated winemakers – his Welschriesling delivers incredible depth and salty minerality.",
        "tags": ["wine", "white wine", "Welschriesling", "Milan Šukal", "Moravia"]
    },
    {
        "id": "bile-palava-michlovsky",
        "name": "Pálava Vinselekt Michlovský",
        "category": "wine_white",
        "categoryName": "White Wines",
        "producer": "Vinselekt Michlovský",
        "origin": "Czech Republic",
        "region": "Moravia, Mikulov subregion, Perná",
        "volume": "0.75l",
        "abv": "13.0% ABV",
        "price": "620 CZK",
        "rawIngredients": "100% Pálava grape (Czech indigenous cross of Gewürztraminer and Müller Thurgau bred by Ing. Josef Veverka).",
        "productionProcess": "Cryomaceration and precise controlled fermentation directed by renowned enologist Doc. Miloš Michlovský.",
        "flavorProfile": "Intoxicating floral bouquet of tea rose, blooming jasmine, mandarin peel, lychee fruit, and sweet vanilla spice.",
        "foodPairing": "Unrivalled match for duck foie gras pâté, spicy Asian dishes, and semi-soft cheeses.",
        "staffNotes": "The most famous indigenous Moravian variety made by legendary winemaker Miloš Michlovský. Lush body and lingering aromatic finish.",
        "tags": ["wine", "white wine", "Pálava", "Michlovský", "aromatic"]
    },
    {
        "id": "bile-riesling-eva-fricke",
        "name": "Riesling Rheingau Eva Fricke",
        "category": "wine_white",
        "categoryName": "White Wines",
        "producer": "Eva Fricke",
        "origin": "Germany",
        "region": "Rheingau, Lorch / Kiedrich (steep slate slopes)",
        "volume": "0.75l",
        "abv": "12.0% ABV",
        "price": "1,190 CZK",
        "rawIngredients": "100% Riesling from ancient, biodynamically farmed bush vines rooted in pure blue and grey slate.",
        "productionProcess": "Spontaneous native yeast fermentation, slow maturation without additives or chemical fining.",
        "flavorProfile": "Absolute purity, crystalline salty minerality, green citrus, quince, white peach, and laser-sharp precision.",
        "foodPairing": "World-class with lobster bisque, oysters, pan-roasted trout, and dishes featuring yuzu glaze.",
        "staffNotes": "Eva Fricke is an international icon in Rheingau (regular 100-point ratings from Robert Parker). A true jewel on the Fuze wine list.",
        "tags": ["wine", "white wine", "Riesling", "Rheingau", "Germany", "biodynamic"]
    },
    {
        "id": "bile-chardonnay-knotty-vines",
        "name": "Chardonnay Knotty Vines",
        "category": "wine_white",
        "categoryName": "White Wines",
        "producer": "Knotty Vines",
        "origin": "USA",
        "region": "California (Central Coast / Lodi)",
        "volume": "0.75l",
        "abv": "13.5% ABV",
        "price": "690 CZK",
        "rawIngredients": "100% Chardonnay grapes from sun-drenched Californian valley vineyards.",
        "productionProcess": "Partial malolactic fermentation and aging in toasted French and American oak barrels.",
        "flavorProfile": "Rich, creamy, buttery Chardonnay layered with baked yellow apples, pineapple, crème brûlée, and toasted brioche.",
        "foodPairing": "Flawless with roasted pork belly, bacon cheddar burgers, and creamy pasta dishes.",
        "staffNotes": "Quintessential California Chardonnay style – luscious, round, and buttery with an elegant oak kiss.",
        "tags": ["wine", "white wine", "Chardonnay", "California", "USA", "oak"]
    },

    # --- RED WINES ---
    {
        "id": "cervene-pinot-noir-rouci-kraus",
        "name": "Pinot Noir Roučí Kraus",
        "category": "wine_red",
        "categoryName": "Red Wines",
        "producer": "Kraus Winery",
        "origin": "Czech Republic",
        "region": "Bohemia, Mělník subregion, Klamovka vineyard",
        "volume": "0.75l",
        "abv": "13.0% ABV",
        "price": "750 CZK",
        "rawIngredients": "100% Pinot Noir (Roučí clone) cultivated on limestone and marl terraces above the Elbe River.",
        "productionProcess": "Traditional open-vat maceration followed by 12 months aging in French barrique oak barrels.",
        "flavorProfile": "Translucent ruby with brick hues. Aromas of wild strawberries, sour cherries, cranberries, and forest floor with a gentle cedar smoke kiss.",
        "foodPairing": "Beef Wellington, duck breast, foie gras terrine, and veal sausage with morels.",
        "staffNotes": "Professor Kraus was a legend of Czech viticulture. This Bohemian Pinot Noir proves that northern Czech terroirs produce world-class Burgundian elegance.",
        "tags": ["wine", "red wine", "Pinot Noir", "Mělník", "Bohemia", "barrique"]
    },
    {
        "id": "cervene-dornfelder-bilkovi",
        "name": "Dornfelder Bílkovi",
        "category": "wine_red",
        "categoryName": "Red Wines",
        "producer": "Bílkovi Winery",
        "origin": "Czech Republic",
        "region": "Moravia, Velké Pavlovice subregion, Velké Bílovice",
        "volume": "0.75l",
        "abv": "12.5% ABV",
        "price": "520 CZK",
        "rawIngredients": "100% Dornfelder.",
        "productionProcess": "Maceration on skins with gentle pneumatic pressing preserving fruit-forward, approachable tannins.",
        "flavorProfile": "Deep inky garnet hue. Expressive aromas of ripe blackberries, damson plums, blueberries, and forest fruit with velvety soft tannins.",
        "foodPairing": "Great with our beef burger, slow-roasted pork ribs, and charcuterie.",
        "staffNotes": "An approachable, fruit-driven red wine with mild tannins and mesmerizing deep purple color.",
        "tags": ["wine", "red wine", "Dornfelder", "Moravia", "Bílkovi"]
    },
    {
        "id": "cervene-cuvee-red-kolby",
        "name": "Cuvée Red Kolby",
        "category": "wine_red",
        "categoryName": "Red Wines",
        "producer": "Kolby Winery",
        "origin": "Czech Republic",
        "region": "Moravia, Mikulov subregion, Pouzdřany (Kolby vineyard)",
        "volume": "0.75l",
        "abv": "13.5% ABV",
        "price": "790 CZK",
        "rawIngredients": "Bordeaux blend of Cabernet Sauvignon (60%) and Merlot (40%) from the sun-drenched Pouzdřany steppe slopes.",
        "productionProcess": "Aged 14 months in premium French oak barriques (30% new oak).",
        "flavorProfile": "Full-bodied Bordeaux profile. Blackcurrants, blackberries, dark chocolate, pipe tobacco, leather, and cedar wood.",
        "foodPairing": "The perfect companion for US Prime beef rump cap, rib eye, and wood-fired pastrami.",
        "staffNotes": "Superb Moravian interpretation of a grand Bordeaux red. Structured tannins and remarkable aging potential.",
        "tags": ["wine", "red wine", "cuvée", "Cabernet", "Merlot", "Kolby"]
    },
    {
        "id": "cervene-cabernet-lapis-luna",
        "name": "Cabernet Sauvignon Lapis Luna",
        "category": "wine_red",
        "categoryName": "Red Wines",
        "producer": "Lapis Luna Wines",
        "origin": "USA",
        "region": "California, Lodi",
        "volume": "0.75l",
        "abv": "14.0% ABV",
        "price": "790 CZK",
        "rawIngredients": "Cabernet Sauvignon blended with touches of Merlot and Sangiovese from select California vineyards.",
        "productionProcess": "Aged 10 months in French and American oak barrels.",
        "flavorProfile": "Deep purple in the glass. Explosive aromas of ripe blackberries, black cherries, sweet vanilla, roasted espresso beans, and warm baking spices.",
        "foodPairing": "US Prime rib eye, grilled pork belly, and bacon cheeseburger.",
        "staffNotes": "For guests seeking a bold, opulent California red with warm fruit intensity and supple tannins.",
        "tags": ["wine", "red wine", "Cabernet Sauvignon", "California", "USA"]
    },
    {
        "id": "cervene-zinfandel-hendry",
        "name": "Zinfandel Hendry",
        "category": "wine_red",
        "categoryName": "Red Wines",
        "producer": "Hendry Ranch",
        "origin": "USA",
        "region": "California, Napa Valley",
        "volume": "0.75l",
        "abv": "14.8% ABV",
        "price": "1,450 CZK",
        "rawIngredients": "100% Zinfandel from old-vine blocks on the historic Hendry family ranch at the foot of the Mayacamas Mountains in Napa.",
        "productionProcess": "Aged 15 months in French oak barrels. Small-lot artisanal production from dry-farmed heritage vineyards.",
        "flavorProfile": "Concentrated wild raspberry jam, blueberries, cracked black pepper, cloves, dark cocoa, and sweet liquorice with an expansive warming finish.",
        "foodPairing": "The ultimate pairing for beer-braised pork ribs with apple BBQ glaze, US Prime burgers, and pastrami.",
        "staffNotes": "Cult Napa Valley Zinfandel crafted by George Hendry. A benchmark of complex, balanced, non-jammy California Zinfandel.",
        "tags": ["wine", "red wine", "Zinfandel", "Napa Valley", "California"]
    },

    # --- SPARKLING WINES & BUBBLES ---
    {
        "id": "bubliny-charmat-palava",
        "name": "Charmat de Vinselekt Pálava",
        "category": "wine_sparkling",
        "categoryName": "Sparkling Wines & Crémant",
        "producer": "Vinselekt Michlovský",
        "origin": "Czech Republic",
        "region": "Moravia, Mikulov subregion",
        "volume": "0.75l (also by the glass 0.1l)",
        "abv": "12.0% ABV",
        "price": "590 CZK (bottle) / 89 CZK (glass)",
        "rawIngredients": "100% Pálava grapes.",
        "productionProcess": "Charmat method – secondary tank fermentation preserving vibrant primary floral and fruit aromas.",
        "flavorProfile": "Vibrant perlage, delicate aromas of blooming roses, tropical fruit, and citrus with a crisp, dry palate.",
        "foodPairing": "The perfect welcome toast and aperitif before beef tartare and cold starters.",
        "staffNotes": "Our signature house sparkling wine poured by the glass – elegant, fragrant, and refreshing bubbles from Moravia.",
        "tags": ["bubbles", "sparkling wine", "Pálava", "aperitif", "Michlovský"]
    },
    {
        "id": "bubliny-cremant-vinselekt",
        "name": "Crémant de Vinselekt (Pinot Noir & Chardonnay)",
        "category": "wine_sparkling",
        "categoryName": "Sparkling Wines & Crémant",
        "producer": "Vinselekt Michlovský",
        "origin": "Czech Republic",
        "region": "Moravia",
        "volume": "0.75l",
        "abv": "12.5% ABV",
        "price": "890 CZK",
        "rawIngredients": "Classic Champagne cuvée blend: Chardonnay and Pinot Noir.",
        "productionProcess": "Méthode traditionnelle – bottle-fermented and aged on fine lees in bottle for over 24 months.",
        "flavorProfile": "Tiny persistent bubbles, aromas of toasted brioche, roasted hazelnuts, crisp green apples, and chalky mineral finish.",
        "foodPairing": "Oysters, lobster soup, duck foie gras pâté, and crispy fried chicken wings.",
        "staffNotes": "Moravian crémant crafted with the exact same labor-intensive traditional bottle method as authentic Champagne.",
        "tags": ["crémant", "traditional method", "Chardonnay", "Pinot Noir", "bubbles"]
    },
    {
        "id": "bubliny-angels-cowboys",
        "name": "Angels & Cowboys Brut Rosé Sparkling",
        "category": "wine_sparkling",
        "categoryName": "Sparkling Wines & Crémant",
        "producer": "Angels & Cowboys",
        "origin": "USA",
        "region": "California, Sonoma County",
        "volume": "0.75l",
        "abv": "12.0% ABV",
        "price": "1,150 CZK",
        "rawIngredients": "Pinot Noir and Chardonnay blend from cool coastal Sonoma vineyard sites.",
        "productionProcess": "Méthode traditionnelle – bottle-fermented and matured on lees for a minimum of 18 months.",
        "flavorProfile": "Pale salmon pink. Notes of wild strawberries, redcurrants, pomegranate, and fresh-baked brioche.",
        "foodPairing": "Magnificent throughout the entire meal from beef tartare to pork belly and hop-cone chocolate desserts.",
        "staffNotes": "Stylish Sonoma sparkling rosé combining eye-catching design with brilliant crisp freshness.",
        "tags": ["bubbles", "rosé", "sparkling", "California", "USA"]
    },

    # --- RUMS ---
    {
        "id": "rum-havana-club-3",
        "name": "Havana Club Añejo 3 Años",
        "category": "rum",
        "categoryName": "Rums 0.03l",
        "producer": "Havana Club (Corporación Cuba Ron)",
        "origin": "Cuba",
        "region": "Santa Cruz del Norte / San José de Las Lajas",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "66 CZK",
        "rawIngredients": "Cuban sugar cane molasses and mountain spring water.",
        "productionProcess": "Continuous column distillation, aged for a minimum of 3 years in white American oak bourbon casks under Maestros del Ron Cubano, then charcoal filtered.",
        "flavorProfile": "Pale straw hue. Fresh aromas of crushed sugar cane, gentle oak, citrus zest, vanilla, and subtle smoke.",
        "foodPairing": "The authentic foundation for Cuban classic cocktails: Mojito and Daiquiri.",
        "staffNotes": "Genuine Cuban 3-year aged white rum – unlike cheap unaged white rums, this rum actually rests in oak casks for three full years to build real depth.",
        "tags": ["rum", "Cuba", "white rum", "sugar cane", "mojito"]
    },
    {
        "id": "rum-el-dorado-12y",
        "name": "El Dorado 12y",
        "category": "rum",
        "categoryName": "Rums 0.03l",
        "producer": "Demerara Distillers Ltd.",
        "origin": "Guyana",
        "region": "Demerara River Valley",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "98 CZK",
        "rawIngredients": "100% Demerara sugar cane molasses from the lush Demerara river basin.",
        "productionProcess": "Distilled in historic 250-year-old wooden pot stills (Enmore and Port Mourant). Aged at least 12 years in oak bourbon barrels in Guyana's tropical climate.",
        "flavorProfile": "Deep glowing amber. Dark molasses, honey, dried prunes, golden raisins, baked banana, cinnamon, and rich pipe tobacco.",
        "foodPairing": "Fabulous alongside BBQ pork ribs and Valrhona chocolate desserts.",
        "staffNotes": "The age statement 12 signifies the youngest rum in the blend (unlike solera systems). The antique wooden stills impart legendary richness.",
        "tags": ["rum", "Guyana", "Demerara", "12 years", "caramel"]
    },
    {
        "id": "rum-mount-gay-xo",
        "name": "Mount Gay XO Triple Cask",
        "category": "rum",
        "categoryName": "Rums 0.03l",
        "producer": "Mount Gay Distilleries (established 1703)",
        "origin": "Barbados",
        "region": "St. Lucy",
        "volume": "0.03l",
        "abv": "43.0% ABV",
        "price": "148 CZK",
        "rawIngredients": "Barbadian sugar cane molasses and coral-filtered island water.",
        "productionProcess": "Traditional double copper pot still and column distillation. Blend of rums aged 5 to 17 years in three distinct casks: American whiskey, bourbon, and cognac barrels.",
        "flavorProfile": "Exceptionally balanced dry rum. Salted vanilla, ripe figs, candied orange peel, dark cocoa, toasted almonds, and warm oak spice.",
        "foodPairing": "Splendid with US Prime rib eye and as a refined post-dinner sipping spirit.",
        "staffNotes": "Mount Gay is the world's oldest documented commercial rum distillery (est. 1703). XO is not artificially sweetened – it is pure, bone-dry artisanal rum.",
        "tags": ["rum", "Barbados", "Mount Gay", "dry rum", "oldest distillery"]
    },
    {
        "id": "rum-abuelo-7y",
        "name": "Abuelo Añejo 7 Años",
        "category": "rum",
        "categoryName": "Rums 0.03l",
        "producer": "Varela Hermanos",
        "origin": "Panama",
        "region": "Pesé, Herrera Valley",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "82 CZK",
        "rawIngredients": "Virgin cane honey and estate-grown Panamanian sugar cane molasses.",
        "productionProcess": "Slow fermentation using proprietary yeast strains. Aged 7 years in select white American oak bourbon casks.",
        "flavorProfile": "Golden amber. Gentle notes of caramel, dried dates, toasted nuts, coconut flakes, and mild baking spices.",
        "foodPairing": "Excellent with burgers, raclette sandwiches, and roasted seasonal vegetables.",
        "staffNotes": "A very approachable, silky Panamanian rum offering fantastic character and smoothness.",
        "tags": ["rum", "Panama", "Abuelo", "smooth", "caramel"]
    },
    {
        "id": "rum-eminente-reserva-7y",
        "name": "Eminente Reserva 7y",
        "category": "rum",
        "categoryName": "Rums 0.03l",
        "producer": "Moët Hennessy & Cuba Ron (Master Ronero César Martí)",
        "origin": "Cuba",
        "region": "Villa Clara (Central Cuba)",
        "volume": "0.03l",
        "abv": "41.3% ABV",
        "price": "145 CZK",
        "rawIngredients": "High-grade Cuban sugar cane molasses.",
        "productionProcess": "Unusually high proportion of rich aguardiente (70%) – heavy aromatic pot-still spirits. Aged at least 7 years in white oak whisky casks.",
        "flavorProfile": "Complex, full-bodied. Freshly roasted coffee beans, dark cocoa nibs, ginger root, cured tobacco, prunes, and vanilla bean.",
        "foodPairing": "Magnificent with Valrhona chocolate desserts and a double espresso.",
        "staffNotes": "The textured glass bottle mimics Cuban crocodile skin (Cuba is affectionately called 'Isla del Cocodrilo'). The 70% aguardiente content yields far more depth than typical light Cuban rums.",
        "tags": ["rum", "Cuba", "Eminente", "coffee", "chocolate", "crocodile"]
    },
    {
        "id": "rum-diplomatico",
        "name": "Diplomático Reserva Exclusiva",
        "category": "rum",
        "categoryName": "Rums 0.03l",
        "producer": "Destilerías Unidas S.A. (DUSA)",
        "origin": "Venezuela",
        "region": "La Miel, foothills of the Andes",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "115 CZK",
        "rawIngredients": "Virgin sugar cane honey and select molasses.",
        "productionProcess": "Copper pot still distillation (80%) blended with column spirits. Aged up to 12 years in small American white oak bourbon casks.",
        "flavorProfile": "Velvety sweet and opulent. Creamy toffee, dark chocolate truffles, candied orange peel, maple syrup, and sweet cinnamon.",
        "foodPairing": "Caramelized Kaiserschmarrn, roasted spiced plums, and malt desserts.",
        "staffNotes": "One of the world's favorite premium sipping rums. Ideal for guests who love smooth, dessert-like richness.",
        "tags": ["rum", "Venezuela", "Diplomatico", "sweet rum", "vanilla"]
    },
    {
        "id": "rum-zacapa-23y",
        "name": "Ron Zacapa Centenario 23",
        "category": "rum",
        "categoryName": "Rums 0.03l",
        "producer": "Industrias Licoreras de Guatemala (Master Blender Lorena Vásquez)",
        "origin": "Guatemala",
        "region": "Quetzaltenango ('House Above the Clouds', 2,300 m above sea level)",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "155 CZK",
        "rawIngredients": "Virgin sugar cane honey from first-press cane juice (not byproduct molasses).",
        "productionProcess": "Matured in the cool mountain highlands at 2,300 meters via the Sistema Solera process in bourbon, Pedro Ximénez sherry, and French cognac casks.",
        "flavorProfile": "Deep dark mahogany. Noble aromas of dried figs, plump raisins, dark honey, cigar leaf, roasted coffee, nutmeg, and polished oak.",
        "foodPairing": "Superb with US Prime beef steak, chocolate soil dessert, and aged artisan cheeses.",
        "staffNotes": "Royal highland rum aged 'above the clouds'. The cold altitude slows evaporation, yielding incomparable depth and silky softness.",
        "tags": ["rum", "Guatemala", "Zacapa", "Solera", "virgin honey"]
    },

    # --- TEQUILAS & MEZCALS ---
    {
        "id": "tequila-tres-alegres-compadres",
        "name": "Tres Alegres Compadres Blanco",
        "category": "tequila",
        "categoryName": "Tequilas 0.03l",
        "producer": "Tres Alegres Compadres",
        "origin": "Mexico",
        "region": "Jalisco",
        "volume": "0.03l",
        "abv": "38.0% ABV",
        "price": "75 CZK",
        "rawIngredients": "100% blue agave (Agave tequilana Weber azul).",
        "productionProcess": "Traditional brick oven roasting of ripe agave hearts (piñas), crushing, wild fermentation, and double distillation in copper pot stills. Bottled fresh unaged.",
        "flavorProfile": "Crystal clear. Crisp herbal notes of raw and cooked agave, crushed white pepper, lime peel, and green apple freshness.",
        "foodPairing": "The authentic base for Paloma and Margarita cocktails; great with blistered Padrón peppers and chimichurri.",
        "staffNotes": "Pure 100% Blue Weber agave blanco tequila – free from added sugars or additives (no mixtos). A pristine expression of real agave.",
        "tags": ["tequila", "blanco", "Mexico", "100% agave", "Jalisco"]
    },
    {
        "id": "tequila-herradura-reposado",
        "name": "Herradura Reposado",
        "category": "tequila",
        "categoryName": "Tequilas 0.03l",
        "producer": "Casa Herradura (established 1870)",
        "origin": "Mexico",
        "region": "Amatitán, Jalisco",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "115 CZK",
        "rawIngredients": "100% Blue Weber agave harvested after 7 to 10 years of maturity.",
        "productionProcess": "Clay brick ovens, fermented with wild orchard yeasts native to the distillery grounds. Aged 11 months in American white oak barrels (law requires only 2 months).",
        "flavorProfile": "Golden amber. Cooked agave sweetness, rich vanilla, butter caramel, cinnamon, and dried apricots with a warm toasted oak finish.",
        "foodPairing": "Outstanding with grilled pork belly in yuzu glaze and beef tartare.",
        "staffNotes": "Casa Herradura invented the Reposado tequila category in 1974. Resting 11 months gives it richness approaching añejo tequilas.",
        "tags": ["tequila", "reposado", "Herradura", "oak barrels", "Mexico"]
    },
    {
        "id": "tequila-corralejo-reposado",
        "name": "Tequila Corralejo Reposado",
        "category": "tequila",
        "categoryName": "Tequilas 0.03l",
        "producer": "Hacienda Corralejo (established 1755)",
        "origin": "Mexico",
        "region": "Pénjamo, Guanajuato (historic certified DO outside Jalisco)",
        "volume": "0.03l",
        "abv": "38.0% ABV",
        "price": "98 CZK",
        "rawIngredients": "100% Agave Azul Weber.",
        "productionProcess": "Slow roasting in stone ovens, double distillation in copper pot stills using the Charentais method (used in Cognac production). Matured 4 months across French, American, and Mexican oak casks.",
        "flavorProfile": "Pale golden straw presented in an iconic tall blue bottle. Notes of roasted agave, white pepper, vanilla bean, cardamom, and fresh wood.",
        "foodPairing": "Excellent with pastrami, wood-roasted chicken, and spicy mayonnaise.",
        "staffNotes": "The slender cobalt blue bottle is instantly recognizable. The French Charentais distillation method produces remarkable smoothness.",
        "tags": ["tequila", "reposado", "Corralejo", "blue bottle", "Mexico"]
    },
    {
        "id": "tequila-cofradia-rose-catrina",
        "name": "La Cofradia Reposado Rosé „ed. Catrina”",
        "category": "tequila",
        "categoryName": "Tequilas 0.03l",
        "producer": "Tequila La Cofradía",
        "origin": "Mexico",
        "region": "Tequila, Jalisco",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "145 CZK",
        "rawIngredients": "100% blue agave from the Jalisco highlands.",
        "productionProcess": "Traditional cooking and distillation. Specially matured in French oak casks that previously held fine Cabernet Sauvignon red wine, imparting a delicate pink blush and red berry fruitiness.",
        "flavorProfile": "Gentle rosé pink tint. Fragrant cooked agave, fresh strawberries, redcurrants, vanilla, and gentle oak tannins.",
        "foodPairing": "Superb pairing with duck foie gras pâté and cherry desserts.",
        "staffNotes": "A unique pink reposado tequila presented in a hand-painted ceramic Catrina skull bottle celebrating Día de los Muertos.",
        "tags": ["tequila", "reposado", "Catrina", "rosé", "wine cask", "ceramic"]
    },
    {
        "id": "tequila-cofradia-black-catrina",
        "name": "La Cofradia Black „ed. Catrina”",
        "category": "tequila",
        "categoryName": "Tequilas 0.03l",
        "producer": "Tequila La Cofradía",
        "origin": "Mexico",
        "region": "Tequila, Jalisco",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "165 CZK",
        "rawIngredients": "100% blue agave.",
        "productionProcess": "Traditional baking and distillation, followed by extended aging in deeply charred American white oak casks.",
        "flavorProfile": "Dark amber. Complex notes of wood smoke, roasted agave, dark chocolate, espresso beans, oak spice, and dried fruit.",
        "foodPairing": "US Prime beef steaks from the grill and braised pork ribs.",
        "staffNotes": "Bottled in an iconic black ceramic Catrina skull. An impressive sipping experience both in presentation and palate depth.",
        "tags": ["tequila", "añejo", "Catrina", "black edition", "ceramic skull"]
    },

    # --- WHISKY, WHISKEY & BOURBON ---
    {
        "id": "whisky-goldcock-blended",
        "name": "Goldcock Blended Whisky",
        "category": "whisky",
        "categoryName": "Whisky, Whiskey, Bourbon 0.03l",
        "producer": "Rudolf Jelínek (originally Těšetice u Olomouce)",
        "origin": "Czech Republic",
        "region": "Moravia, Vizovice / Haná plain",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "68 CZK",
        "rawIngredients": "100% Moravian barley malt and grains from the fertile Haná region, Vizovice spring water.",
        "productionProcess": "Distilled on Arnold Holstein pot stills, aged in virgin toasted casks coopered from local Czech winter oak.",
        "flavorProfile": "Golden color. Malty, sweet vanilla, crisp green apple, orchard honey, rolled oats, and toasted oak.",
        "foodPairing": "Great with glazed pork ribs and veal sausage with morels.",
        "staffNotes": "Czech cult whisky with roots dating back to 1973. Aged exclusively in native Czech oak casks harvested in Moravian forests.",
        "tags": ["whisky", "Czech whisky", "Goldcock", "malt", "Czech oak"]
    },
    {
        "id": "whisky-glenfiddich-15y",
        "name": "Glenfiddich 15y Solera Reserve",
        "category": "whisky",
        "categoryName": "Whisky, Whiskey, Bourbon 0.03l",
        "producer": "William Grant & Sons (Glenfiddich Distillery)",
        "origin": "Scotland",
        "region": "Speyside (Dufftown)",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "145 CZK",
        "rawIngredients": "100% malted barley and Robbie Dhu spring water.",
        "productionProcess": "Speyside Single Malt matured in three woods: Spanish Oloroso sherry, American bourbon, and virgin oak. Married in an immense handcrafted Oregon pine Solera vat that has remained half-full continuously since 1998.",
        "flavorProfile": "Immensely silky and complex. Sherry sweetness, marzipan, dark raisins, cinnamon, ginger, baked apple, and mellow oak.",
        "foodPairing": "Beef Wellington, duck foie gras, and caramelized Kaiserschmarrn.",
        "staffNotes": "Pioneering Speyside single malt. The Solera vat system ensures magnificent consistency, silkiness, and aromatic depth.",
        "tags": ["whisky", "single malt", "Scotland", "Speyside", "Solera", "Glenfiddich"]
    },
    {
        "id": "whisky-talisker-10y",
        "name": "Talisker 10y",
        "category": "whisky",
        "categoryName": "Whisky, Whiskey, Bourbon 0.03l",
        "producer": "Talisker Distillery (established 1830)",
        "origin": "Scotland",
        "region": "Isle of Skye (Carbost)",
        "volume": "0.03l",
        "abv": "45.8% ABV",
        "price": "148 CZK",
        "rawIngredients": "Heavily peated Scottish malted barley and peaty water from Cnoc nan Speireag.",
        "productionProcess": "Double distilled in unique swan-neck copper pot stills with U-shaped worm tubs, aged 10 years in American oak casks right on the windswept Atlantic shores of Skye.",
        "flavorProfile": "Powerful maritime peat smoke, sea salt spray, sweet malt, dried citrus peel, and the iconic explosive black pepper finish ('peppery catch').",
        "foodPairing": "Brilliant with lobster soup, smoked pork belly, and hand-cut beef tartare.",
        "staffNotes": "The oldest distillery on the Isle of Skye. Author Robert Louis Stevenson hailed it as 'the king o' drinks'.",
        "tags": ["whisky", "single malt", "smoky", "Isle of Skye", "Talisker", "peat"]
    },
    {
        "id": "whisky-monkey-shoulder",
        "name": "Monkey Shoulder Blended Malt",
        "category": "whisky",
        "categoryName": "Whisky, Whiskey, Bourbon 0.03l",
        "producer": "William Grant & Sons",
        "origin": "Scotland",
        "region": "Speyside",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "98 CZK",
        "rawIngredients": "100% malted barley (Blended Malt – composed strictly of single malts with zero grain neutral spirit).",
        "productionProcess": "Expertly blended from three premier Speyside distilleries (Balvenie, Glenfiddich, and Kininvie). Aged in first-fill bourbon casks.",
        "flavorProfile": "Supremely creamy and accessible. Vanilla custard, golden honey, poached pears, orange marmalade, and delicate nutmeg oak spice.",
        "foodPairing": "Delicious enjoyed neat on ice or in classic whisky cocktails (Old Fashioned, Whisky Sour).",
        "staffNotes": "Named in honor of maltmen who suffered temporary strain from hand-turning barley, affectionately known as 'monkey shoulder'.",
        "tags": ["whisky", "blended malt", "Speyside", "vanilla", "smooth"]
    },
    {
        "id": "whiskey-jameson",
        "name": "Jameson Irish Whiskey",
        "category": "whisky",
        "categoryName": "Whisky, Whiskey, Bourbon 0.03l",
        "producer": "Irish Distillers (Midleton Distillery)",
        "origin": "Ireland",
        "region": "County Cork, Midleton",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "75 CZK",
        "rawIngredients": "Malted and unmalted barley dried in closed kilns free of peat smoke, pure Irish water.",
        "productionProcess": "Triple distilled in copper pot stills and continuous columns, aged at least 4 years in bourbon and Oloroso sherry casks.",
        "flavorProfile": "Exceptionally gentle and balanced. Crisp green apples, vanilla, roasted hazelnuts, and delicate floral notes with a silky non-smoky finish.",
        "foodPairing": "Pairs easily with burgers, roasted chicken, and pork knuckle.",
        "staffNotes": "The world's bestselling Irish whiskey. Triple distillation and zero peat smoke make it remarkably smooth and approachable.",
        "tags": ["whiskey", "Ireland", "Jameson", "triple distilled", "smooth"]
    },
    {
        "id": "whiskey-jack-daniels",
        "name": "Jack Daniel's Old No. 7",
        "category": "whisky",
        "categoryName": "Whisky, Whiskey, Bourbon 0.03l",
        "producer": "Jack Daniel Distillery (established 1866)",
        "origin": "USA",
        "region": "Lynchburg, Tennessee",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "82 CZK",
        "rawIngredients": "Mash bill: 80% corn, 12% malted barley, 8% rye. Iron-free limestone water from Cave Spring Hollow.",
        "productionProcess": "Tennessee Whiskey – slowly mellowed drop by drop through 10 feet of sugar maple charcoal before barrel entry (Lincoln County Process), then matured in new charred American white oak casks.",
        "flavorProfile": "Sweet, smoky, full-bodied. Brown sugar, vanilla, roasted bananas, maple syrup, and toasted oak.",
        "foodPairing": "Classic with beer-braised pork ribs in apple BBQ sauce and beef burgers.",
        "staffNotes": "Not an ordinary bourbon: maple charcoal mellowing imparts Jack Daniel's signature smooth, sweet maple character.",
        "tags": ["whiskey", "Tennessee", "Jack Daniels", "charcoal mellowed", "USA"]
    },

    # --- BRANDY & COGNAC ---
    {
        "id": "brandy-metaxa-5",
        "name": "Metaxa ***** (5 Stars)",
        "category": "brandy_cognac",
        "categoryName": "Brandy & Cognac 0.03l",
        "producer": "House of Metaxa (Spyros Metaxa, est. 1888)",
        "origin": "Greece",
        "region": "Kifissia / Aegean Islands (Samos & Lemnos)",
        "volume": "0.03l",
        "abv": "38.0% ABV",
        "price": "68 CZK",
        "rawIngredients": "Aged wine distillates, sun-drenched Muscat wines from Aegean islands, secret Mediterranean herbal extracts, and May rose petals.",
        "productionProcess": "Wine spirits age at least 5 years in French Limousin oak barrels, then married with sweet Muscat wine and botanicals.",
        "flavorProfile": "Warm amber hue. Honeyed apricot, orange blossom, rosewater, sweet raisins, vanilla, and gentle oak spice.",
        "foodPairing": "Pleasant alongside espresso, sweet pastries, and caramelized Kaiserschmarrn.",
        "staffNotes": "A singular Greek spirit – fine aged wine brandy softened with aromatic island Muscat wine and rose petals.",
        "tags": ["brandy", "Greece", "Metaxa", "Muscat wine", "herbs"]
    },
    {
        "id": "cognac-remy-martin-1738",
        "name": "Rémy Martin 1738 Accord Royal",
        "category": "brandy_cognac",
        "categoryName": "Brandy & Cognac 0.03l",
        "producer": "Rémy Martin (established 1724)",
        "origin": "France",
        "region": "Cognac, Fine Champagne (Grande & Petite Champagne)",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "175 CZK",
        "rawIngredients": "Ugni Blanc grapes grown in the premier limestone terroirs of Grande and Petite Champagne.",
        "productionProcess": "Double distilled on lees in small Charentais copper pot stills. Aged in heavily toasted French Limousin oak casks.",
        "flavorProfile": "Generous and opulent. Plum marmalade, dried figs, sweet liquorice, dark chocolate, cinnamon, and toffee with an endless finish.",
        "foodPairing": "Beef Wellington, duck foie gras, and luxury Valrhona Dulcey chocolate desserts.",
        "staffNotes": "In 1738, King Louis XV of France granted Rémy Martin the royal privilege to plant new vines for exceptional quality. This cognac proudly bears that historic date.",
        "tags": ["cognac", "Fine Champagne", "France", "Remy Martin", "royal accord"]
    },

    # --- SPIRITS & LIQUEURS ---
    {
        "id": "palenka-fuzovice",
        "name": "Fuzovice (Beer Eau-de-Vie)",
        "category": "liqueur_spirit",
        "categoryName": "Spirits & Liqueurs 0.03l",
        "producer": "FUZE Brewery & Restaurant in collaboration with an artisanal craft distillery",
        "origin": "Czech Republic",
        "region": "Prague",
        "volume": "0.03l",
        "abv": "42.0% ABV",
        "price": "85 CZK",
        "rawIngredients": "Freshly brewed unpasteurized, unfiltered TransFUZE 12 pale lager from our in-house brewery.",
        "productionProcess": "Slow fractional pot-still distillation of our house-brewed lager, capturing the delicate essential oils of Moravian malt and Saaz hops.",
        "flavorProfile": "Crystal clear beer brandy. Aromas of freshly cracked brewery malt, herbal Saaz hops, fresh bread crust, and baked orchard fruit.",
        "foodPairing": "The supreme digestive after pork knuckle, ribs, and beef burgers.",
        "staffNotes": "Our signature signature spirit! Crafted by distilling our own TransFUZE 12 craft beer – an authentic story to share with every guest.",
        "tags": ["beer brandy", "FUZE", "in-house", "TransFUZE", "craft"]
    },
    {
        "id": "palenka-absinth-st-antoine",
        "name": "Absinth St. Antoine Žufánek",
        "category": "liqueur_spirit",
        "categoryName": "Spirits & Liqueurs 0.03l",
        "producer": "Žufánek Family Distillery (Boršice)",
        "origin": "Czech Republic",
        "region": "Moravia, Slovácko",
        "volume": "0.03l",
        "abv": "70.0% ABV",
        "price": "115 CZK",
        "rawIngredients": "Neutral spirit, grand wormwood (Artemisia absinthium), green anise, Florence fennel, and 7 Alpine botanicals.",
        "productionProcess": "Traditional distillation without artificial colors. Secondary herb maceration gives natural emerald chlorophyll color.",
        "flavorProfile": "Potent, herbal, fresh aniseed flavor with balanced wormwood bitterness and clean fennel. Dilution with ice water produces an instant milky louche effect.",
        "foodPairing": "Served with the traditional ritual of cold iced water dripped through a slotted spoon with sugar.",
        "staffNotes": "Martin Žufánek produces one of Europe's most revered genuine absinthes. Never set on fire – true absinthe is gently diluted with iced water!",
        "tags": ["absinth", "Žufánek", "herbs", "wormwood", "70%", "louche"]
    },
    {
        "id": "palenka-kminka-garage22",
        "name": "Kmínka Caraway Liqueur (Garage 22)",
        "category": "liqueur_spirit",
        "categoryName": "Spirits & Liqueurs 0.03l",
        "producer": "Garage 22 (Craft distillery in Holešovice, Prague)",
        "origin": "Czech Republic",
        "region": "Prague, Holešovice",
        "volume": "0.03l",
        "abv": "38.0% ABV",
        "price": "89 CZK",
        "rawIngredients": "Czech biennial caraway, Roman cumin, citrus peel, and botanical herbs.",
        "productionProcess": "Macerated and gently redistilled on a small copper column still in Prague's hip Holešovice district.",
        "flavorProfile": "Noble, warming, spicy spirit highlighting crusty rye caraway bread nuances brightened with a fresh citrus lift.",
        "foodPairing": "Incomparable after hearty meats, roast pork knuckle, and beef tartare.",
        "staffNotes": "Caraway has been used for centuries across Central Europe to aid digestion after rich feasts. Garage 22 elevates historic Czech Kmínka to contemporary world-class craft.",
        "tags": ["caraway", "Garage 22", "Prague", "digestive", "craft"]
    },
    {
        "id": "palenka-kontusovka-zufanek",
        "name": "Kontušovka Žufánek",
        "category": "liqueur_spirit",
        "categoryName": "Spirits & Liqueurs 0.03l",
        "producer": "Žufánek (Boršice)",
        "origin": "Czech Republic",
        "region": "Moravia, Slovácko",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "95 CZK",
        "rawIngredients": "Star anise, green anise, fennel, coriander, caraway, and five additional botanical herbs.",
        "productionProcess": "Spiced herbal spirit based on a 17th-century Polish-Lithuanian noble recipe, aged in oak casks.",
        "flavorProfile": "Rich golden glow. Opulent star anise and liquorice aromatics, warm spice, and a gentle honeyed undertone.",
        "foodPairing": "Classic digestive after hearty Czech dishes and pork feasts.",
        "staffNotes": "Famous in classic Czech literature ('two Kontušovkas and a beer'). Žufánek resurrected this noble historical spirit with modern finesse.",
        "tags": ["kontušovka", "Žufánek", "star anise", "historic", "liqueur"]
    },
    {
        "id": "palenka-orechovy-radlik",
        "name": "Walnut Liqueur Radlík (Ořechový)",
        "category": "liqueur_spirit",
        "categoryName": "Spirits & Liqueurs 0.03l",
        "producer": "Radlík Distillery (Jílové u Prahy)",
        "origin": "Czech Republic",
        "region": "Central Bohemia",
        "volume": "0.03l",
        "abv": "35.0% ABV",
        "price": "89 CZK",
        "rawIngredients": "Unripe green walnuts harvested around St. John's Day (late June), whole spices (cloves, cinnamon, nutmeg), honey, and fruit eau-de-vie.",
        "productionProcess": "Slow multi-month maceration of green walnuts in fruit spirits, aged to harmonize bitterness and honey sweetness.",
        "flavorProfile": "Dark walnut brown. Rich, pleasant walnut bitterness layered with warm baking spices and velvety honey sweetness.",
        "foodPairing": "Wonderful with cheese platters, nut desserts, and Waldorf salad.",
        "staffNotes": "Radlík is one of the most awarded craft distilleries in the Czech Republic, holding dozens of international medals.",
        "tags": ["walnut", "Radlík", "green walnuts", "herbal liqueur"]
    },
    {
        "id": "palenka-hustopecska-mandlovka",
        "name": "Hustopečská Mandlovka (Almond Spirit)",
        "category": "liqueur_spirit",
        "categoryName": "Spirits & Liqueurs 0.03l",
        "producer": "Mandlárna Hustopeče",
        "origin": "Czech Republic",
        "region": "Moravia, Hustopeče (unique almond orchards)",
        "volume": "0.03l",
        "abv": "38.0% ABV",
        "price": "79 CZK",
        "rawIngredients": "Natural almond essence, wine eau-de-vie spirit, grape juice, and pure water.",
        "productionProcess": "Harmonious blending of wine spirit with natural almond extract following a traditional recipe by former orchard director Rudolf Poslušný.",
        "flavorProfile": "Crystal clear spirit with intoxicating sweet marzipan fragrance and a full, warming sweet-almond finish.",
        "foodPairing": "Delicious with desserts, shredded pancake Kaiserschmarrn, and hot espresso.",
        "staffNotes": "Crafted from Central Europe's only extensive almond orchards blooming on the slopes of southern Moravia.",
        "tags": ["almond", "Hustopeče", "marzipan", "Moravia", "sweet spirit"]
    },
    {
        "id": "palenka-jagermeister",
        "name": "Jägermeister Herbal Liqueur",
        "category": "liqueur_spirit",
        "categoryName": "Spirits & Liqueurs 0.03l",
        "producer": "Mast-Jägermeister SE (established 1878)",
        "origin": "Germany",
        "region": "Wolfenbüttel, Lower Saxony",
        "volume": "0.03l",
        "abv": "35.0% ABV",
        "price": "75 CZK",
        "rawIngredients": "56 distinct natural herbs, blossoms, roots, and fruits (including ginger, star anise, cardamom, bitter orange, liquorice, and juniper).",
        "productionProcess": "Multi-stage maceration in alcohol and water lasting several weeks, then matured for 12 months in massive German oak vats.",
        "flavorProfile": "Dark herbal liqueur. Complex, bittersweet, aromatic with intense notes of cinnamon, clove, and liquorice. Served ice-cold at -18°C.",
        "foodPairing": "Universal ice-cold toast and herbal digestive after rich meals.",
        "staffNotes": "Served directly from the freezer at -18°C for optimal syrupy viscosity and smooth herbal release.",
        "tags": ["Jägermeister", "herbal liqueur", "Germany", "ice-cold", "56 botanicals"]
    },
    {
        "id": "palenka-becherovka",
        "name": "Becherovka Unfiltered",
        "category": "liqueur_spirit",
        "categoryName": "Spirits & Liqueurs 0.03l",
        "producer": "Jan Becher – Karlovarská Becherovka",
        "origin": "Czech Republic",
        "region": "Karlovy Vary (Carlsbad)",
        "volume": "0.03l",
        "abv": "38.0% ABV",
        "price": "68 CZK",
        "rawIngredients": "Secret blend of approximately 20 herbs and exotic spices, Carlsbad mineral water, fine spirit, and sugar.",
        "productionProcess": "Botanical maceration in oak casks. The unfiltered release retains natural cloudiness, offering richer mouthfeel and higher essential oil content.",
        "flavorProfile": "Iconic bittersweet spice profile led by cloves, cinnamon, aniseed, and bitter orange peel.",
        "foodPairing": "Celebrated both as an appetite-whetting aperitif and a traditional digestive aid.",
        "staffNotes": "The unfiltered version is a connoisseur treat – noticeably richer, hazier, and more aromatic than standard Becherovka.",
        "tags": ["Becherovka", "Carlsbad", "herbal liqueur", "unfiltered", "Czech classic"]
    },

    # --- GINS & VODKAS ---
    {
        "id": "gin-tanqueray",
        "name": "Tanqueray London Dry Gin",
        "category": "gin",
        "categoryName": "Gins 0.03l",
        "producer": "Charles Tanqueray (founded in London, 1830)",
        "origin": "United Kingdom",
        "region": "Cameronbridge, Scotland",
        "volume": "0.03l",
        "abv": "43.1% ABV",
        "price": "82 CZK",
        "rawIngredients": "Neutral grain spirit and exactly four pure botanicals: Tuscan juniper, coriander seed, angelica root, and sweet liquorice.",
        "productionProcess": "Quadruple distilled in the historic copper pot still 'Old Tom No. 10', which survived the London Blitz.",
        "flavorProfile": "Pine-fresh, crisp, unadorned London dry profile driven by robust juniper, bright citrus-coriander lift, and a dry finish.",
        "foodPairing": "Perfect with premium Thomas Henry tonic and a fresh lime wedge.",
        "staffNotes": "The global gold standard for London Dry Gin. No artificial flavorings, no added sugar – just 4 perfectly balanced botanicals.",
        "tags": ["gin", "London Dry", "Tanqueray", "juniper", "England"]
    },
    {
        "id": "gin-hendricks",
        "name": "Hendrick's Gin",
        "category": "gin",
        "categoryName": "Gins 0.03l",
        "producer": "William Grant & Sons (Girvan Distillery)",
        "origin": "Scotland",
        "region": "Ayrshire, Girvan",
        "volume": "0.03l",
        "abv": "41.4% ABV",
        "price": "115 CZK",
        "rawIngredients": "11 traditional botanicals complemented by post-distillation infusions of Bulgarian Damask rose petals and crisp Dutch cucumber essence.",
        "productionProcess": "Unique union of two distinct stills: a traditional Bennett pot still (richness) and a rare 1948 Carter-Head still with botanical vapor basket (delicacy).",
        "flavorProfile": "Floral, wonderfully fresh with signature notes of cool cucumber, scented rose petals, and subtle juniper backing.",
        "foodPairing": "Served with Fever-Tree or Thomas Henry tonic water and a thin ribbon of fresh cucumber.",
        "staffNotes": "Bottled in an iconic Victorian apothecary bottle. The gin that sparked the modern craft gin renaissance.",
        "tags": ["gin", "Hendricks", "cucumber", "rose", "Scotland"]
    },
    {
        "id": "vodka-anton-kaapl-legionar",
        "name": "Anton Kaapl LEGIONÄR Vodka",
        "category": "vodka",
        "categoryName": "Vodkas 0.03l",
        "producer": "Anton Kaapl Family Distillery",
        "origin": "Czech Republic",
        "region": "South Bohemia, Jílovice",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "89 CZK",
        "rawIngredients": "Extra-fine rectified grain spirit and crystal demineralized water drawn from deep artesian wells in the Novohradské Mountains.",
        "productionProcess": "Multi-stage multi-day active charcoal filtration, followed by resting in stainless vats for ultimate smoothness.",
        "flavorProfile": "Immensely silky, clean, pure mouthfeel with zero harsh burn and a faint hint of sweet wheat grain on the finish.",
        "foodPairing": "Traditional accompaniment to beef tartare, caviar, consommé, and smoked meats.",
        "staffNotes": "Award-winning craft distillery from South Bohemia named after the family grandfather – Czechoslovak legionnaire Anton Kaapl.",
        "tags": ["vodka", "Anton Kaapl", "South Bohemia", "pure", "craft"]
    },
    {
        "id": "vodka-grey-goose",
        "name": "Grey Goose Vodka",
        "category": "vodka",
        "categoryName": "Vodkas 0.03l",
        "producer": "Bacardi (François Thibault, Maître de Chai)",
        "origin": "France",
        "region": "Picardy / Cognac (Gensac-la-Pallue)",
        "volume": "0.03l",
        "abv": "40.0% ABV",
        "price": "135 CZK",
        "rawIngredients": "100% French soft winter wheat from Picardy and natural limestone-filtered spring water from Gensac-la-Pallue in Cognac.",
        "productionProcess": "Five-step continuous column distillation and blending with Cognac limestone spring water.",
        "flavorProfile": "Velvety, rounded texture with gentle nuances of sweet almond, white pepper, and fresh bakery dough.",
        "foodPairing": "The luxury foundation for Vodka Martinis, Espresso Martinis, and Cosmopolitans.",
        "staffNotes": "Synonymous with luxury French vodka, created by a cellar master from the heart of the Cognac region.",
        "tags": ["vodka", "Grey Goose", "France", "wheat", "luxury"]
    },

    # --- IN-HOUSE CRAFT BEERS ON TAP ---
    {
        "id": "pivo-transfuze-12",
        "name": "TransFUZE 12 (Traditional Lager)",
        "category": "beer_craft",
        "categoryName": "Beer on Tap",
        "producer": "FUZE Prague In-House Brewery (Brewmaster Aleš Paik)",
        "origin": "Czech Republic",
        "region": "Prague, Masaryčka",
        "volume": "0.3l / 0.5l",
        "abv": "5.0% ABV",
        "price": "59 CZK / 69 CZK",
        "rawIngredients": "Floor-malted Czech barley malt, native Saaz semi-early red-bine hops (Žatecký poloraný červeňák), pure brewing water, bottom-fermenting lager yeast.",
        "productionProcess": "Traditional double-decoction mashing, open fermentation vessels, and long lagering in horizontal tanks. Unpasteurized, unfiltered, poured straight from conditioning tanks.",
        "flavorProfile": "Golden brilliant color, thick creamy foam cap, rich bready malt body balanced by clean, delicious, non-cloying hop bitterness.",
        "foodPairing": "Universal companion for Czech specialties: thick-cut Duroc schnitzel, beef tartare, and roasted pork knuckle.",
        "staffNotes": "Our flagship brew! Brewed right in our restaurant by head brewmaster Aleš Paik. Fresh, unfiltered Czech lager at its absolute peak.",
        "tags": ["beer", "lager", "FUZE", "TransFUZE", "on tap", "tank beer"]
    },
    {
        "id": "pivo-infuze-ipa-12",
        "name": "InFUZE IPA 12 (Session IPA)",
        "category": "beer_craft",
        "categoryName": "Beer on Tap",
        "producer": "FUZE Prague In-House Brewery (Brewmaster Aleš Paik)",
        "origin": "Czech Republic",
        "region": "Prague",
        "volume": "0.4l",
        "abv": "4.9% ABV",
        "price": "85 CZK",
        "rawIngredients": "Pale barley malts, dry-hopped with aromatic American and New Zealand hop varieties (Citra, Mosaic, Nelson Sauvin).",
        "productionProcess": "Top-fermented ale, cold dry-hopped directly in conditioning tanks, unpasteurized and unfiltered.",
        "flavorProfile": "Vibrant citrus aromas of pink grapefruit, passion fruit, and fresh pine needles, light refreshing body, and a clean dry bitter finish.",
        "foodPairing": "Pairs exceptionally with burgers, pork belly with chimichurri, and spicy dishes.",
        "staffNotes": "Session IPA is designed to be intensely fragrant with lush hop oils while staying refreshingly light and drinkable all evening long.",
        "tags": ["beer", "IPA", "Session IPA", "FUZE", "hops", "citrus"]
    },
    {
        "id": "pivo-fuzenac-13",
        "name": "FUZEnáč 13 (Smoked Amber Lager)",
        "category": "beer_craft",
        "categoryName": "Beer on Tap",
        "producer": "FUZE Prague In-House Brewery (Brewmaster Aleš Paik)",
        "origin": "Czech Republic",
        "region": "Prague",
        "volume": "0.3l / 0.5l",
        "abv": "5.3% ABV",
        "price": "69 CZK / 78 CZK",
        "rawIngredients": "Floor-malted barley, authentic beechwood-smoked malt from Bamberg, caramel malts, and Saaz hops.",
        "productionProcess": "Bottom-fermented amber lager, slow tank lagering, unpasteurized and unfiltered.",
        "flavorProfile": "Gorgeous amber glow, distinctive campfire smoke aroma, full-bodied malt profile with subtle caramel sweetness.",
        "foodPairing": "Genius pairing with hop-smoked pork belly, clay-oven pastrami, and beer-glazed ribs.",
        "staffNotes": "For lovers of authentic smoked lagers (Rauchbier). The beechwood smoke imparts incredible savory character.",
        "tags": ["beer", "amber", "smoked", "Rauchbier", "FUZE", "specialty"]
    }
]

print(f"Loaded {len(BEVERAGE_ITEMS_EN)} English beverage items")
